# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader


[[mods]] #mandatory
modId="exampleblock" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Example Block" #mandatory
logoFile="exampleblock.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Exampole Block
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.exampleblock]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.exampleblock]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"


[[mods]] #mandatory
modId="exampleitem" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Example Item" #mandatory

logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional

description='''
Example Item description
'''
[[dependencies.exampleitem]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[41,)" #mandatory
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.exampleitem]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
